services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build

build:
  stage: build
  only:
    - master
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest